---
- name: install golang
  homebrew: name=golang state=present
- name: create go dev environment
  file: path={{ item }} state=directory
  with_items:
  - "{{ go_path }}"
  - "{{ go_path }}/bin"
  - "{{ go_path }}/pkg"
  - "{{ go_path }}/src"
